@startuml classdiag

class Leg {
    {field}
    -LA[]
}

class nucleo {
    {field}
    -serial
    {method}
    -send(float)
}

class LinearActuator {
    {method}
    -go_to(float)
    {field}
}

class Motor {
    {field}
    -nucleo
    -leg
    -motor
    {method}
    -go_to_serialized(float)
}

Leg *-- LinearActuator: 3
Motor *-- LinearActuator 

@enduml